### ISSUE TITLE
Is BouncyCastle.Cryptography package the official replacement of Portable.BouncyCastle package?

### ISSUE THREAD

**Issue by tonyqus** [novotnyllc/bc-csharp#108]
Someone comes to me mentions that NPOI should use BouncyCastle.Cryptography instead. I'm not sure what's the relationship between these two packages. Can you help clarify?

Related issue: https://github.com/nissl-lab/npoi/issues/1007

**Comment by OzBob** [comment]
I don't know the definitive answer to your question but I will quote from [the release notes for BouncyCastle.Cryptography 2.0.0](https://bouncycastle.org/csharp/index.html#DOWNLOAD20201) which is now on [Nuget](https://www.nuget.org/packages/BouncyCastle.Cryptography/2.0.0)



> **Release Notes for 2.0.0**
> With this release we have finally moved to building for modern .NET versions (directly targeted frameworks: net461, netstandard2.0, net6.0), and distributing using NuGet (package name BouncyCastle.Cryptography). We have also adopted [Semantic Versioning 2.0.0](https://semver.org/) for package versioning.

> There are backward compatibility breaks with this release, but they are minor and the overall process of migrating from either Release 1.9.0 (or [Portable.BouncyCastle](https://www.nuget.org/packages/Portable.BouncyCastle)) should be smooth for most users. The legacy TLS implementation (Org.BouncyCastle.Crypto.Tls) has been removed and users should migrate to the new implementation (Org.BouncyCastle.Tls).

> **Dedication**
> This release is dedicated to [Claire Novotny](https://github.com/clairernovotny), who has been keeping the project alive for the past several years in the form of the [Portable.BouncyCastle](https://www.nuget.org/packages/Portable.BouncyCastle) NuGet package."

**Comment by tonyqus** [comment]
Thank you!
