### ISSUE TITLE
Cannot seem to use with Xamarin Forms NET Standard 2.0 app

### ISSUE THREAD

**Issue by dwhiteddsoft** [novotnyllc/bc-csharp#11]
Fails in Link on iOS side with the following error:
MTOUCH: Error MT2001: Could not link assemblies. Reason: Error while processing references of 'Mobilev2.iOS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' (MT2001) 

With diagnostics build on this line pops out: 
    --- inner exception
    Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'BouncyCastle.Crypto, Version=1.8.2.0, Culture=neutral, PublicKeyToken=0e99375e54769942' --->

**Comment by clairernovotny** [comment]
There's nothing ios specific about this. Seems like the library isn't being copied to the right output directory? I'd open an issue with Microsoft.
