### ISSUE TITLE
Not able to build on Visual Studio

### ISSUE THREAD

**Issue by rahulsu** [novotnyllc/bc-csharp#12]
Hi
  I have my server  application, that is based on DotNet core.
  I am evaluating this 'bc-sharp' as a standalone application ( with as is, not mixed with my aplicatio n yest) to play how I can generate certificate etc.
   I am using Visual Studio 2017. Loaded the solution file, and when I build I am seeing the below issues: Can you please help me and advise how to get around this issue. Its possible I may be doing some basic thing wrong, but not able to find it. 

Severity	Code	Description	Project	File	Line	Suppression State

Error	CS0006	Metadata file 'C:\bc-csharp-netstandard\crypto\src\bin\Debug\netstandard2.0\BouncyCastle.Crypto.dll' could not be found	crypto.test(netcoreapp2.0)	C:\bc-csharp-netstandard\crypto\test\CSC	1	Active

Error	CS0006	Metadata file 'C:\bc-csharp-netstandard\crypto\src\bin\Debug\netstandard1.3\BouncyCastle.Crypto.dll' could not be found	crypto.test(netcoreapp2.0)	C:\bc-csharp-netstandard\crypto\test\CSC	1	Active

Error		Unable to locate repository containing directory 'C:\bc-csharp-netstandard\crypto\src'.	crypto	C:\Users\rahul.suraparaju\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta-63127-02\build\Microsoft.Build.Tasks.Git.targets	20	

Error		Unable to locate repository containing directory 'C:\bc-csharp-netstandard\crypto\src'.	crypto	C:\Users\rahul.suraparaju\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta-63127-02\build\Microsoft.Build.Tasks.Git.targets	20	

Error		Unable to locate repository containing directory 'C:\bc-csharp-netstandard\crypto\src'.	crypto	C:\Users\rahul.suraparaju\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta-63127-02\build\Microsoft.Build.Tasks.Git.targets	20	

Error		Unable to locate repository containing directory 'C:\bc-csharp-netstandard\crypto\src'.	crypto	C:\Users\rahul.suraparaju\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta-63127-02\build\Microsoft.Build.Tasks.Git.targets	20	

Error	MSB3644	The reference assemblies for framework ".NETFramework,Version=v4.6.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.	crypto.test	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	1179

**Comment by clairernovotny** [comment]
Hi,

I'm not sure what you're trying to do. If you want to use the package, the easiest way is to install it from NuGet:
https://www.nuget.org/packages/Portable.BouncyCastle/
