### ISSUE TITLE
Choice of .Net Standard 1.0 vs 1.1

### ISSUE THREAD

**Issue by rastrup** [novotnyllc/bc-csharp#15]
Seing the implemented versions of .Net Standard 1.0 and 1.1 there is no difference:
https://docs.microsoft.com/en-us/dotnet/standard/net-standard
So you could change .Net Standard 1.0 to 1.1 without any compability issues.

**Comment by clairernovotny** [comment]
Why does it matter at this point, what are you trying to do?

**Comment by rastrup** [comment]
Seing how long the previous version of framework got to live in this project it would make sence to implement as high a level as possible because it might take 10 years again before the next time.
.Net Standard 1.1 opens up for CLR versions of Compression streams and BigInteger instead of the custom ones now used.
And there would be no issues in changing.

**Comment by clairernovotny** [comment]
.NET Framework 4.5.2, which is the lowest supported version of .NET Framework, supports .NET Standard 1.2. .NET 4.5 and 4.5.1 have been out of support for a long time and should not be run in production...

**Comment by rastrup** [comment]
That is correct but currently the netstandard branch builds for .Net Framework 4.0 and .Net Standard 1.0, 1.3 & 2.0
And i say you can replace the 1.0 with a 1.1 without any issues.

**Comment by clairernovotny** [comment]
.NET Framework 4.0 is not supported anymore either. I will not actively support unsupported .NET Framework versions, sorry.

The current package supports all supported versions of the .NET on all platforms.

**Comment by rastrup** [comment]
I am not saying what you are supporting, but what you are building for `<TargetFrameworks>netstandard2.0;netstandard1.3;netstandard1.0;net4</TargetFrameworks>`
Taken from https://github.com/onovotny/bc-csharp/blob/netstandard/crypto/src/crypto.csproj

**Comment by clairernovotny** [comment]
Sorry, I misunderstood.

At this point, there's no need to target anything else as this release is based purely on the upstream. I won't accept changes that are specifically to this repo, any changes need to be made in the BC repo. What platforms they target is their choice.

**Comment by rastrup** [comment]
But this is the csproj file made specifically for the netstandard build so only in that branch.

**Comment by clairernovotny** [comment]
Closing as no platform that's < NET Standard 2.0 is supported by Microsoft and there's a .NET 4 target as well.
