### ISSUE TITLE
Rebuild Portable.BouncyCastle NuGet package from source?

### ISSUE THREAD

**Issue by osmedd** [novotnyllc/bc-csharp#31]
My apologies if I missed this... but I have a requirement to rebuild the (1.8.5) Portable.BouncyCastle NuGet package from source for .NET Core.  I am sure this isn't rocket science but the first few shots I have taken have not been successful.

Is there a preferred Visual Studio version?  Can I open one/all of the solution files and build and then run the nuget pack command?  My simple attempts at using the various solution files have not been very successful.  Is this simplest using nant?

Thanks,
Owen

**Comment by osmedd** [comment]
Looking at the newer netstandard branch, I saw the crypto/src/crypto.csproj file that did everything I needed.  I added this to the source from bccrypto-csharp-1.8.5-src.zip, removed the non-.NET Standard bits, and I could 'dotnet build' and 'dotnet pack' a Portable.BouncyCastle nuget package.  Assuming testing goes well I will close this issue.

**Comment by clairernovotny** [comment]
Closing due to age.
