### ISSUE TITLE
NuGet package author changed

### ISSUE THREAD

**Issue by jariq** [novotnyllc/bc-csharp#4]
Hello Oren,

I've been using your BC package for quite a while (thanks for maintaining it) and I've always known the correct BC package is *"Portable.BouncyCastle by **Oren Novotny**"*:

![image](https://user-images.githubusercontent.com/1163818/36932640-38d62b96-1ecc-11e8-80dc-787aed1d68c5.png)

However in 1.8.1.4 it changed to *"Portable.BouncyCastle by **BouncyCastle.Crypto**"*: 

![image](https://user-images.githubusercontent.com/1163818/36932635-16ab3fde-1ecc-11e8-826f-5e32fba81a18.png)

Was this change intentional?

**Comment by clairernovotny** [comment]
No, that's a bug.

**Comment by clairernovotny** [comment]
Thanks, fixed. Of course, the question is if it's worth posting a package update for that given that there aren't any code changes?

**Comment by jariq** [comment]
I personally don't need the updated version now that I'm aware this is your/correct package. Feel free to close this issue.

**Comment by clairernovotny** [comment]
I'll get a new version of all of my packages, including this one, published to NuGet once they enable package signing.
