### ISSUE TITLE
.NET Core 2.0 Package?

### ISSUE THREAD

**Issue by timotei** [novotnyllc/bc-csharp#5]
Hello,

It seems that currently we are being offered a .NET Core 1.x package. Are there any plans to offer the 2.0 variant? For example, a very important class that allows us to work with openssl-based RSA private keys is `DotNetUtilities` (https://github.com/onovotny/bc-csharp/blob/netstandard/crypto/src/security/DotNetUtilities.cs), which can be used under .NET Core 2.0

I tried understading how we generate the package only for .NET Standard 1.3 and not for 2.0 also, but no luck with that :( The dotnet pack documentation doesn't say the default target framework.

Thanks!

**Comment by clairernovotny** [comment]
Not sure I follow? The `Portable.BouncyCastle` NuGet package contains a netstandard1.0, 1.3, and 2.0 version. The `DotNetUtilities` is available in the `netstandard2.0` version. When you reference the nuget package, it'll automatically use the "best/highest" version your plaform supports.

**Comment by timotei** [comment]
Well, I only see the 1.3 one: https://www.nuget.org/packages/BouncyCastle.NetCore/:

```
 Dependencies
.NETStandard 1.3
NETStandard.Library (>= 1.6.0)
System.Reflection (>= 4.3.0)
System.Reflection.TypeExtensions (>= 4.1.0)
```

**Comment by timotei** [comment]
Oh, I think I was looking at the wrong package 🤔 

This one: https://www.nuget.org/packages/Portable.BouncyCastle indeed contains the different versions.

**Comment by clairernovotny** [comment]
This repo is for `Portable.BouncyCastle`. happy to help if you run into any issues specific to the portable version there :)

**Comment by timotei** [comment]
OK, let's close this issue then :) Seems it works as expected

**Comment by elbro** [comment]
This `DotNetUtilities` package is still missing for me in a new netcoreapp2.0 project, I can see it is using the netstandard2.0 version....

`dotnet new webapi`
`dotnet add package Portable.BouncyCastle`

netcoreapp2.0 should support netstandard2.0?
