### ISSUE TITLE
Catchin exception when parsing pfx gost 3410 2012

### ISSUE THREAD

**Issue by murtazo96** [novotnyllc/bc-csharp#54]
Cathing exception message "Value cannot be null"  when parsing cer and key from pfx(gost 3410 2012)
          try
            {
                // Load my gost 3410 2012 certificate and private key form PKCS12 container
                var store = new Pkcs12Store();
                using (var strm = File.OpenRead(@"my.pfx"))
                    store.Load(strm, new[] { '1' });
                var alias = store.Aliases.Cast<string>().First();
                var cert = store.GetCertificate(alias).Certificate;
                var privKey = store.GetKey(alias).Key;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);//Value cannot be null. (Parameter 'source')
            }

**Comment by clairernovotny** [comment]
This issue should be raised at https://github.com/bcgit/bc-csharp as this fork is just for building the portable version.
