### ISSUE TITLE
InvalidCastException when parsing a code sign p7b

### ISSUE THREAD

**Issue by acoder84** [novotnyllc/bc-csharp#69]
```
 var p7b = File.ReadAllBytes(path);
 var cmsSignedData = new Org.BouncyCastle.Cms.CmsSignedData(p7b);
```
System.InvalidCastException: Unable to cast object of type 'Org.BouncyCastle.Asn1.DerSequence' to type 'Org.BouncyCastle.Asn1.Asn1OctetString'.
   at Org.BouncyCastle.Cms.CmsSignedData..ctor(ContentInfo sigData) in /crypto/src/cms/CMSSignedData.cs:line 138
   at Org.BouncyCastle.Cms.CmsSignedData..ctor(Byte[] sigBlock) in /crypto/src/cms/CMSSignedData.cs:line 62

https://github.com/novotnyllc/bc-csharp/blob/55456f239cef1cc403f24055be548a6c74694373/crypto/src/cms/CMSSignedData.cs#L138

Consider checking the type of `signedData.EncapContentInfo.Content` before casting.

File for test (rename to .p7b)
[BouncyCastle.Crypto.zip](https://github.com/novotnyllc/bc-csharp/files/6916058/BouncyCastle.Crypto.zip)

**Comment by clairernovotny** [comment]
This bug should be opened in https://github.com/bcgit/bc-csharp. The only issues that should be here are ones related to this fork directly.
