### ISSUE TITLE
ThreadedSeedGenerator blocks when setting SecureRandom

### ISSUE THREAD

**Issue by bpiepiora** [novotnyllc/bc-csharp#73]
The following while loop and its use in the DoGenerateSeed-method makes me a bit nervous... Since it's missing any command to Sleep, Delay or something, this mechanism quite often blocks in our application when calling `new SecureRandom()`. I think this code is only used in the portable version(?). Nonetheless, it should be reworked, if there is any future use planned.

https://github.com/novotnyllc/bc-csharp/blob/0f827cc3e74a8f45669fba5c525adacd6b897503/crypto/src/crypto/prng/ThreadedSeedGenerator.cs#L31-L38

https://github.com/novotnyllc/bc-csharp/blob/0f827cc3e74a8f45669fba5c525adacd6b897503/crypto/src/crypto/prng/ThreadedSeedGenerator.cs#L59-L124

See for yourself:
    
    for (int i = 0; i < 10_000; i++)
    {
        System.Console.WriteLine("Start - " + i);
        byte[] res = new ThreadedSeedGenerator().GenerateSeed(32, true);
        System.Console.WriteLine("End   - " + i);
    }

**Comment by clairernovotny** [comment]
Hi @bpiepiora, general issues for BC should be filed in the upstream repo https://github.com/bcgit/bc-csharp
 
I can only address issues specific to the portable version here. 

This library does not define PORTABLE so that code is not used. 

Thanks!

**Comment by bpiepiora** [comment]
Okay! Thanks for the information
