### ISSUE TITLE
System.NullReferenceException: at Org.BouncyCastle.Asn1.DerOctetString..ctor

### ISSUE THREAD

**Issue by ghost** [novotnyllc/bc-csharp#81]
https://github.com/novotnyllc/bc-csharp/blob/60196c784a98efb64c8a04b7e0385973fd57bc2a/crypto/src/cms/KeyTransRecipientInfoGenerator.cs#L38-L42

subjectKeyIdentifier is always null in this ctor. This seems to be a typo from https://github.com/novotnyllc/bc-csharp/commit/01238566c1d4b2a606e4859a75ad05ca79db4ffb

**Comment by clairernovotny** [comment]
Hi,

Thanks for finding a bug -- this fork can only accept PRs that are specific to building the netstandard version. Please submit the bug/PR to the upstream repo to ensure it gets fixed for everyone: 

https://github.com/bcgit/bc-csharp
