### ISSUE TITLE
Question re: usage with PowerShell module

### ISSUE THREAD

**Issue by rmbolger** [novotnyllc/bc-csharp#9]
I have an existing PowerShell module targetting Win PowerShell 5.1 (and .NET 4.7.1) that currently bundles the 1.8.2 BouncyCastle.Crypto.dll distributed directly from bouncycastle.org. It's loaded via `RequiredAssemblies` in the module manifest. I'm currently working on adding PowerShell Core 6 compatibility which I believe sits on .NET Core 2.0. 

According to @terrajobst's [.NET Standard version table](http://immo.landwerth.net/netstandard-versions), I think that means I should switch to using the `netstandard2.0` build of the [Portable.BouncyCastle](https://www.nuget.org/packages/Portable.BouncyCastle) nuget package. Do I understand things correctly?

Also, I've been testing on a WSL Ubuntu 16.04 instance with the `6.0.2-1.ubuntu.16.04` powershell package, but I haven't switched to the portable version of the DLL yet and everything still seems to work as far as BouncyCastle is concerned. Does that just mean I haven't hit a code path that would fail on Linux yet? What danger (if any) do I face by not switching to the Portable version?

**Comment by clairernovotny** [comment]
Yes, for PowerShell Core 6, the `netstandard2.0` version should work for you. I can't say for sure how that works with PowerShell 5.1 on .NET 4.7.1, but I believe it should work there too. The `netstandard2.0` version has everything the `net4` version does.

**Comment by rmbolger** [comment]
Awesome. Thanks a ton!
